import { useEffect } from "react";
import { InsightsLegalLayout } from "@/components/insights-legal-layout";

export default function Terms() {
  useEffect(() => { window.scrollTo(0, 0); }, []);
  return (
    <InsightsLegalLayout>
      <div className="max-w-3xl mx-auto px-6 lg:px-10 pt-16 pb-20">
        <h1 className="text-3xl lg:text-4xl font-bold mb-2" style={{ color: "#1a2035" }}>AVANA Insights — Terms and Conditions</h1>
        <p className="text-sm mb-10" style={{ color: "#6b7280" }}>Last updated: April 2026</p>

        <div className="space-y-8 text-sm leading-relaxed" style={{ color: "#374151" }}>
          <section>
            <h2 className="text-lg font-bold mb-3" style={{ color: "#1a2035" }}>1. About these Terms</h2>
            <p>
              These supplemental Terms and Conditions ("Insights Terms") govern your use of <strong>AVANA Insights</strong> — our AI-native data intelligence platform — operated by AVANA Services Limited, a company registered in England and Wales (Company Number: 15268633) ("AVANA", "we", "us", "our").
            </p>
            <p className="mt-3">
              The Insights Terms apply alongside the master <a href="/services-ai/terms" style={{ color: "#4CAF50" }}>AVANA Services Terms and Conditions</a>, which cover account registration, acceptable use, intellectual property, fees, limitation of liability, termination, governing law, and other shared provisions. Where the Insights Terms address a topic specifically, they take precedence; otherwise the master AVANA Services Terms apply unchanged.
            </p>
            <p className="mt-3">
              By using AVANA Insights, you confirm that you have read and accept both these Insights Terms and the master AVANA Services Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-3" style={{ color: "#1a2035" }}>2. Insights-Specific Definitions</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>"Connected Source"</strong> means any third-party data system you authorise AVANA Insights to access — for example a CRM, ERP, accounting system, e-commerce platform, spreadsheet, file store or database (e.g. HubSpot, Salesforce, Xero, Shopify, Google Sheets, PostgreSQL).</li>
              <li><strong>"Customer Data"</strong> means the metadata, schemas, records, files and other content ingested or referenced from your Connected Sources, together with the questions you ask of that data and the resulting answers, dashboards and decision reports.</li>
              <li><strong>"Insight"</strong> means an AI-generated answer, summary, chart or analytical output produced from your Customer Data.</li>
              <li><strong>"Lineage"</strong> means the references AVANA Insights surfaces alongside an Insight — for example evidence quotes, source rows or files — that show which Customer Data the Insight was derived from.</li>
              <li><strong>"Decision Report"</strong> means a structured report generated by AVANA Insights setting out options, risks, evidence and confidence around a question.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-3" style={{ color: "#1a2035" }}>3. Connected Sources</h2>
            <p>When you connect a Connected Source to AVANA Insights, you:</p>
            <ul className="list-disc pl-5 space-y-2 mt-3">
              <li>Authorise AVANA to access, ingest, index and process the data exposed by that connection, on your behalf, for the purpose of providing the Services.</li>
              <li>Confirm that you have the necessary rights and permissions to share that data with AVANA, including under any contracts, licences, customer consents and applicable data-protection laws.</li>
              <li>Acknowledge that your use of the third-party service itself remains subject to that provider's own terms, and that AVANA is not responsible for the availability, accuracy, completeness or behaviour of that third-party service.</li>
              <li>May disconnect the Connected Source at any time. After disconnection, AVANA will cease ingesting new data from that source and will delete or anonymise the previously ingested data within a commercially reasonable period, subject to any backup, audit-log and legal-retention obligations.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-3" style={{ color: "#1a2035" }}>4. Customer Data — Ownership and Licence</h2>
            <p>
              You (or your organisation) retain ownership of all Customer Data. You grant AVANA a limited, non-exclusive, worldwide, royalty-free licence to host, copy, process, index and analyse Customer Data solely to (a) deliver, secure and operate AVANA Insights for you, (b) generate Insights, dashboards and Decision Reports for your authorised users, and (c) maintain Lineage references back to your sources.
            </p>
            <p className="mt-3">
              AVANA processes Customer Data on your instructions, as a Data Processor under the UK GDPR, subject to a Data Processing Agreement.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-3" style={{ color: "#1a2035" }}>5. AI Insights and Decision Reports</h2>
            <p>
              AVANA Insights uses artificial intelligence to translate your natural-language questions into queries over your Customer Data and to generate Insights, dashboards and Decision Reports. You acknowledge that:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-3">
              <li>Insights are produced algorithmically from the Customer Data available at the time of the query and are intended as guidance only.</li>
              <li>We do not guarantee the accuracy, completeness, currency or fitness for purpose of any Insight, dashboard or Decision Report.</li>
              <li>Lineage is provided to help you trace and validate the source of any Insight; you are responsible for reviewing the underlying evidence before relying on an Insight.</li>
              <li>Financial, operational, strategic, legal and compliance decisions remain your responsibility and must always involve appropriate human review.</li>
              <li>AVANA is not liable for any decisions made or actions taken based solely on AI-generated Insights or Decision Reports.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-3" style={{ color: "#1a2035" }}>6. No Training on Customer Data</h2>
            <p>
              AVANA does not use Customer Data to train generalised public AI models. Customer Data is used solely to operate AVANA Insights for the customer that owns it, including generating Insights, building Lineage and improving the customer's own experience. Aggregate, fully de-identified usage statistics may be used to improve platform reliability and performance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-3" style={{ color: "#1a2035" }}>7. Customer Responsibility for Source Compliance</h2>
            <p>
              You are responsible for ensuring that the data you connect to AVANA Insights is lawful for you to share with us — including in respect of personal data, customer/contractual confidentiality, regulated data and any internal access controls. You should not connect data sources that you are not entitled to share with a third-party processor, and you should configure your Connected Sources to expose only the data your AVANA Insights workspace requires.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-3" style={{ color: "#1a2035" }}>8. Other Terms (Defer to Master)</h2>
            <p>
              All other matters — including account registration, acceptable use, intellectual property in the Platforms themselves, fees and payment, limitation of liability, termination, changes to terms and governing law — are governed by the <a href="/services-ai/terms" style={{ color: "#4CAF50" }}>master AVANA Services Terms and Conditions</a>. Please read them in conjunction with this document.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-3" style={{ color: "#1a2035" }}>9. Contact Us</h2>
            <p>If you have any questions about these Insights Terms, please contact us at:</p>
            <div className="mt-3 p-4 rounded-lg" style={{ backgroundColor: "#f8f9fb", border: "1px solid #e5e7eb" }}>
              <p className="font-semibold" style={{ color: "#1a2035" }}>AVANA Services Limited</p>
              <p>Company Number: 15268633</p>
              <p>Registered Office: 85 Great Portland Street, London, W1W 7LT</p>
              <p className="mt-2">
                Email: <a href="mailto:enquiries@avanaservices.com" style={{ color: "#4CAF50" }}>enquiries@avanaservices.com</a>
              </p>
            </div>
          </section>
        </div>
      </div>
    </InsightsLegalLayout>
  );
}
