import { Router, type IRouter } from "express";
import healthRouter from "./health";
import jobsRouter from "./jobs";
import candidatesRouter from "./candidates";
import matchesRouter from "./matches";
import companyProfileRouter from "./companyProfile";
import companyTeamRouter from "./companyTeam";
import storageRouter from "./storage";
import adminRouter from "./admin";
import favouritesRouter from "./favourites";
import contactRouter from "./contact";
import featureRequestsRouter from "./featureRequests";
import accountRouter from "./account";
import verificationsRouter from "./verifications";
import passwordResetRouter from "./passwordReset";
import emailVerificationRouter from "./emailVerification";
import bookmarksRouter from "./bookmarks";
import chatRouter from "./chat";
import jobAlertsRouter from "./jobAlerts";
import candidateAlertsRouter from "./candidateAlerts";
import devTasksRouter from "./devTasks";
import devOptionsRouter from "./devOptions";
import authRouter from "./auth";
import parseCvRouter from "./parseCv";
import recruiterPitchRouter from "./recruiterPitch";
import cvRewriteRouter from "./cvRewrite";
import industriesRouter from "./industries";
import jobsAiRouter from "./jobsAi";
import savedSearchesRouter from "./savedSearches";
import sessionsRouter from "./sessions";
import insightsRouter from "./insights";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(jobsRouter);
router.use(candidatesRouter);
router.use(matchesRouter);
router.use(companyProfileRouter);
router.use(companyTeamRouter);
router.use(storageRouter);
router.use(adminRouter);
router.use(favouritesRouter);
router.use(bookmarksRouter);
router.use(contactRouter);
router.use(featureRequestsRouter);
router.use(accountRouter);
router.use(verificationsRouter);
router.use(passwordResetRouter);
router.use(emailVerificationRouter);
router.use(chatRouter);
router.use(jobAlertsRouter);
router.use(candidateAlertsRouter);
router.use(devTasksRouter);
router.use(devOptionsRouter);
router.use(parseCvRouter);
router.use(recruiterPitchRouter);
router.use(cvRewriteRouter);
router.use(industriesRouter);
router.use(jobsAiRouter);
router.use(savedSearchesRouter);
router.use(sessionsRouter);
router.use(insightsRouter);

export default router;
