export const CITY_SUGGESTIONS: string[] = [
  "London, UK",
  "Manchester, UK",
  "Birmingham, UK",
  "Leeds, UK",
  "Liverpool, UK",
  "Sheffield, UK",
  "Bristol, UK",
  "Newcastle, UK",
  "Nottingham, UK",
  "Leicester, UK",
  "Coventry, UK",
  "Southampton, UK",
  "Portsmouth, UK",
  "Brighton, UK",
  "Reading, UK",
  "Oxford, UK",
  "Cambridge, UK",
  "Milton Keynes, UK",
  "York, UK",
  "Norwich, UK",
  "Plymouth, UK",
  "Exeter, UK",
  "Bournemouth, UK",
  "Bath, UK",
  "Cardiff, UK",
  "Swansea, UK",
  "Newport, UK",
  "Edinburgh, UK",
  "Glasgow, UK",
  "Aberdeen, UK",
  "Dundee, UK",
  "Inverness, UK",
  "Belfast, UK",
  "Derry, UK",
  "Dublin, Ireland",
  "Cork, Ireland",
  "Galway, Ireland",
  "Limerick, Ireland",
  "Waterford, Ireland",

  "New York, USA",
  "Los Angeles, USA",
  "Chicago, USA",
  "Houston, USA",
  "Phoenix, USA",
  "Philadelphia, USA",
  "San Antonio, USA",
  "San Diego, USA",
  "Dallas, USA",
  "Austin, USA",
  "San Francisco, USA",
  "Seattle, USA",
  "Boston, USA",
  "Denver, USA",
  "Washington, DC, USA",
  "Miami, USA",
  "Atlanta, USA",
  "Portland, USA",
  "Las Vegas, USA",
  "Detroit, USA",

  "Toronto, Canada",
  "Montreal, Canada",
  "Vancouver, Canada",
  "Calgary, Canada",
  "Ottawa, Canada",
  "Edmonton, Canada",

  "Paris, France",
  "Lyon, France",
  "Marseille, France",
  "Toulouse, France",
  "Nice, France",
  "Berlin, Germany",
  "Munich, Germany",
  "Hamburg, Germany",
  "Frankfurt, Germany",
  "Cologne, Germany",
  "Stuttgart, Germany",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Valencia, Spain",
  "Seville, Spain",
  "Rome, Italy",
  "Milan, Italy",
  "Naples, Italy",
  "Turin, Italy",
  "Florence, Italy",
  "Amsterdam, Netherlands",
  "Rotterdam, Netherlands",
  "The Hague, Netherlands",
  "Brussels, Belgium",
  "Antwerp, Belgium",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Bern, Switzerland",
  "Vienna, Austria",
  "Lisbon, Portugal",
  "Porto, Portugal",
  "Stockholm, Sweden",
  "Gothenburg, Sweden",
  "Oslo, Norway",
  "Copenhagen, Denmark",
  "Helsinki, Finland",
  "Warsaw, Poland",
  "Krakow, Poland",
  "Prague, Czech Republic",
  "Budapest, Hungary",
  "Athens, Greece",
  "Istanbul, Turkey",

  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
  "Christchurch, New Zealand",

  "Mumbai, India",
  "Delhi, India",
  "Bangalore, India",
  "Hyderabad, India",
  "Chennai, India",
  "Kolkata, India",
  "Pune, India",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Kyoto, Japan",
  "Seoul, South Korea",
  "Beijing, China",
  "Shanghai, China",
  "Shenzhen, China",
  "Hong Kong",
  "Singapore",
  "Bangkok, Thailand",
  "Kuala Lumpur, Malaysia",
  "Jakarta, Indonesia",
  "Manila, Philippines",
  "Ho Chi Minh City, Vietnam",

  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Doha, Qatar",
  "Riyadh, Saudi Arabia",
  "Tel Aviv, Israel",
  "Cape Town, South Africa",
  "Johannesburg, South Africa",

  "Sao Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Buenos Aires, Argentina",
  "Mexico City, Mexico",
  "Santiago, Chile",
  "Bogota, Colombia",
  "Lima, Peru",

  "Remote",
  "Remote (UK)",
  "Remote (Europe)",
  "Remote (Worldwide)",
];
