// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/candidate-onboarding/AllSet.tsx": () => import("../components/mockups/candidate-onboarding/AllSet.tsx"),
  "./components/mockups/candidate-onboarding/Skills.tsx": () => import("../components/mockups/candidate-onboarding/Skills.tsx"),
  "./components/mockups/candidate-onboarding/Welcome.tsx": () => import("../components/mockups/candidate-onboarding/Welcome.tsx"),
  "./components/mockups/ideal-candidate/CandidateDisplay.tsx": () => import("../components/mockups/ideal-candidate/CandidateDisplay.tsx"),
  "./components/mockups/ideal-candidate/JobFormSection.tsx": () => import("../components/mockups/ideal-candidate/JobFormSection.tsx")
};
